In [3]:
import numpy as hah
a=hah.array([1,2,3,4])
print(a)

[1 2 3 4]


In [39]:
import numpy as hah
a=hah.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(a)
b=hah.zeros((3,4))
print("THE ELEMENT IN ARRAY IS",b)
c=hah.full((3,3),7)
print(c)
d=hah.random.random((3,3))
print(d)
e=hah.arange(10,99,15)
print(e)
a.reshape(4,4)
print(a)
f=a.flatten()
print(f)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
g=a.astype('f')
print(g)
print(a)
print(a[0:3:2])


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
THE ELEMENT IN ARRAY IS [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]
[[0.76224245 0.69060033 0.94475643]
 [0.3647531  0.46106752 0.09017524]
 [0.19547109 0.83721671 0.50185688]]
[10 25 40 55 70 85]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
2
(4, 4)
16
int32
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1  2  3  4]
 [ 9 10 11 12]]


In [9]:
import numpy as hah
arr=hah.array([[-1,2,0,4],
             [4,-0.5,6,0],
             [2.6,0,7,8],
             [3,-7,4,2.0]])


In [10]:
#Original array
print("Original array:\n",arr)


Original array:
 [[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]
 [ 2.6  0.   7.   8. ]
 [ 3.  -7.   4.   2. ]]


In [11]:
#return every other rows
print("\nEvery other rows:arr[0:3:2]:\n",arr[0:3:2])



Every other rows:arr[0:3:2]:
 [[-1.   2.   0.   4. ]
 [ 2.6  0.   7.   8. ]]


In [12]:
#slicing array
temp=arr[:2,:3]
print("\nArray with first 2 rows and 3 columns:arr[:2,:3]:\n",temp)



Array with first 2 rows and 3 columns:arr[:2,:3]:
 [[-1.   2.   0. ]
 [ 4.  -0.5  6. ]]


In [13]:
#integer array indexing example
temp=arr[[0,1,2,3],[3,2,1,0]]
print("\nElements at indices(0,3),(1,2),(2,1),"
     "(3,0):\n",temp)



Elements at indices(0,3),(1,2),(2,1),(3,0):
 [4. 6. 0. 3.]


In [14]:
#boolean array indexing example
cond=arr>2


In [15]:
#cond is a bollean array
temp=arr[cond]
print("\nElements greater than 2:\n",temp)



Elements greater than 2:
 [4.  4.  6.  2.6 7.  8.  3.  4. ]


In [16]:
#Return every other element from the entire array:
arr=hah.array([1,2,3,4,5,6,7])
print("\noriginal array:",arr)
print("\nReturn every other element from the entire array:arr[::2]:",arr[::2])



original array: [1 2 3 4 5 6 7]

Return every other element from the entire array:arr[::2]: [1 3 5 7]


In [17]:
#joining two array
arr1=hah.array([1,2,3])
arr2=hah.array([4,5,6])
arr=hah.concatenate((arr1,arr2))
print("\nOriginal arrays:\n",arr1,arr2)
print("\nJoined array:\n",arr)



Original arrays:
 [1 2 3] [4 5 6]

Joined array:
 [1 2 3 4 5 6]


In [18]:
#Horizontal join
arr=hah.hstack((arr1,arr2))
print("\nHorizontal joining:\n",arr)



Horizontal joining:
 [1 2 3 4 5 6]


In [19]:
#Vertical join
arr=hah.vstack((arr1,arr2))
print("\nVertical joining:\n",arr)


Vertical joining:
 [[1 2 3]
 [4 5 6]]


In [22]:
#Depth join
arr=hah.dstack((arr1,arr2))
print("\nDepth joining:\n",arr)


Depth joining:
 [[[1 4]
  [2 5]
  [3 6]]]


In [24]:
#splitting array
arr=hah.array([1,2,3,4,5,6])
newarr=hah.array_split(arr,3)
print("\nOriginal Array:\n",arr)
print("\nSplitted array:\n",newarr)


Original Array:
 [1 2 3 4 5 6]

Splitted array:
 [array([1, 2]), array([3, 4]), array([5, 6])]


In [25]:
#Display splitted array in another form
print("\nsplitted array in another form:\n")
print(newarr[0])
print(newarr[1])
print(newarr[2])


splitted array in another form:

[1 2]
[3 4]
[5 6]


In [26]:
import numpy as hah
#indicies where the value is 4:
arr=hah.array([2,3,4,5,6,6])
print("Original array:",arr)
x=hah.where(arr==4)
print("\nIndexes where the value is 4",x)


Original array: [2 3 4 5 6 6]

Indexes where the value is 4 (array([2], dtype=int64),)


In [35]:

#indexes where the values are even:
arr=hah.array([2,3,4,5,6,7])
x=hah.where(arr%2==0)
print("Original array:",arr)
print("\nIndexes where the values are even",x)

Original array: [2 3 4 5 6 7]

Indexes where the values are even (array([0, 2, 4], dtype=int64),)


In [29]:
#indexes where the value 3 should be inserted,starting from the right
x=hah.searchsorted(arr,3,side='left')
print("\nindexes where the value 3 should be inserted,starting from the right:",x)


indexes where the value 3 should be inserted,starting from the right: 1


In [33]:
#Sorting the array
arr=hah.array([3,2,0,1])
print("\nOriginal array:",arr)
print("\nSorted array:",hah.sort(arr))
arr=hah.array([[3,2,4],[5,0,1]])
print("\nOriginal array:",arr)
print("\nSorted array:",hah.sort(arr))


Original array: [3 2 0 1]

Sorted array: [0 1 2 3]

Original array: [[3 2 4]
 [5 0 1]]

Sorted array: [[2 3 4]
 [0 1 5]]


In [34]:
#Filter
arr=cat.array([40,41,42,43])
x=[True,False,True,False]
nrearr=arr[x]
print("\nOriginal array:",arr)
print("\nFilter index:",x)
print("\nFilter array:",newarr)
arr=cat.array([40,41,42,43])
filter_arr=arr>42
newarr=arr[filter_arr]
print("\nOriginal array:",arr)
print("\nFilter array:condition->42:",filter_arr)
print("\nNew array:",newarr)


Original array: [40 41 42 43]

Filter index: [True, False, True, False]

Filter array: [array([1, 2]), array([3, 4]), array([5, 6])]

Original array: [40 41 42 43]

Filter array:condition->42: [False False False  True]

New array: [43]


In [37]:
import numpy as hah
arr1=[10,20,30,40,50]
arr2=[2,4,6,8,10]
a=hah.array(arr1)
b=hah.array(arr2)
print("Original arrays")
print(a)
print(b)
print("\nVector addition")
print(a+b)
print("\nVector subtraction")
print(a-b)
print("\nVector multiplication")
print(a*b)
print("\nVector division")
print(a/b)
print("\nVector Dot product")
print(a.dot(b))
print("\nScalar multiplication")
sclr=5
print("scalar value=",sclr)
print("array=",a)
print("result=",a*sclr)


Original arrays
[10 20 30 40 50]
[ 2  4  6  8 10]

Vector addition
[12 24 36 48 60]

Vector subtraction
[ 8 16 24 32 40]

Vector multiplication
[ 20  80 180 320 500]

Vector division
[5. 5. 5. 5. 5.]

Vector Dot product
1100

Scalar multiplication
scalar value= 5
array= [10 20 30 40 50]
result= [ 50 100 150 200 250]


In [11]:
#Numpy.Vectorize method
def my_func(x,y):
        #"Return x-y if x>y,otherwise return x+y"
    if x>y:
        return x-y
    else:
        return x+y
print("\n\nNumpy.Vectorize method")
print("Return x-y if x>y,otherwise return x+y)")
arr1=[10,4,20]
arr2=[2,3,30]
vec_func=hah.vectorize(my_func)
print("array1:",arr1)
print("array2:",arr2)
print("result:",vec_func(arr1,arr2))



Numpy.Vectorize method
Return x-y if x>y,otherwise return x+y)
array1: [10, 4, 20]
array2: [2, 3, 30]
result: [ 8  1 50]


In [18]:
import pandas as hah
df=hah.DataFrame()
print(df)

import pandas as hah
emp=hah.Series(['Ajith','Jack','Rose','Yatra','Maaraa'])
id=hah.Series([80,90,28,57,49])
frame={'Emp':emp,'ID':id}
result=hah.DataFrame(frame)
print("\nSeries to Data Frame\n")
print(result)

print("\nExtracting one column:\n")
print(result['Emp'])

print("\nAdding new column:\n")
result['ID']=hah.Series([80,90,28,56,89])
result['Age']=hah.Series([19,90,34,67,20])
print(result)

print("\nDeleting new column:\n")
del result['Age']
print(result)

print("\nExtracting the second row:\n")
print(result.loc[1])

print("Slice rows:\n",result[1:4])

d2=hah.DataFrame([['Vicky',100],['Rashid',109]],columns=['Emp','ID'])
print("\nAdding new row values:\n",result.append(d2))

print("\nDeleting particular row:\n",result.drop(2))


Empty DataFrame
Columns: []
Index: []

Series to Data Frame

      Emp  ID
0   Ajith  80
1    Jack  90
2    Rose  28
3   Yatra  57
4  Maaraa  49

Extracting one column:

0     Ajith
1      Jack
2      Rose
3     Yatra
4    Maaraa
Name: Emp, dtype: object

Adding new column:

      Emp  ID  Age
0   Ajith  80   19
1    Jack  90   90
2    Rose  28   34
3   Yatra  56   67
4  Maaraa  89   20

Deleting new column:

      Emp  ID
0   Ajith  80
1    Jack  90
2    Rose  28
3   Yatra  56
4  Maaraa  89

Extracting the second row:

Emp    Jack
ID       90
Name: 1, dtype: object
Slice rows:
      Emp  ID
1   Jack  90
2   Rose  28
3  Yatra  56

Adding new row values:
       Emp   ID
0   Ajith   80
1    Jack   90
2    Rose   28
3   Yatra   56
4  Maaraa   89
0   Vicky  100
1  Rashid  109

Deleting particular row:
       Emp  ID
0   Ajith  80
1    Jack  90
3   Yatra  56
4  Maaraa  89


C:\Users\Tcs\AppData\Local\Temp\ipykernel_13604\2123395490.py:31: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  print("\nAdding new row values:\n",result.append(d2))


In [19]:
import pandas as pd
import numpy as np
print("DataFrame.apply function:\n")
info = pd.DataFrame ([[3, 9]]*4 , columns =['S' ,'R'])
print("\nOriginal DataFrame:\n", info)
print("\nSquare root of DataFrame:\n", info.apply(np.sqrt))
print("\nSum of each column:\n", info.apply(np.sum, axis=0))
print("\nSum of each row:\n", info.apply(np.sum,axis=1))


info=pd.DataFrame([[2,4,6],[1,3,5],[5,8,7]],columns =['X','Y','Z'])
print("\nOriginal DataFrame:\n", info)
print("\nMinimum and Maximum of each column: \n")
print(info.agg(['min','max']))


print("\nDataFrame.Assign function:\n")
d2 = pd.DataFrame([['Sheik',88], ['Prthzz',70]], columns=['Emp','ID'])
print("\nOriginal DataFrame:\n",d2)
d2['Age']=[20,18]
print("\nAdding new column:\n",d2)
d=d2.assign(Sex=['Male','Female'])
print("\nAdding new column:\n",d)


print("\nDataFrame Sort function:\n")
info=pd.DataFrame(np.random.randn(5,2),index=[3,2,0,4,1],columns=['col3','col4'])
print(info)
info2=info.sort_index()
print("\nSort index:\n",info2)
#info = pd.DataFrame({'col3':[7,1,8,3],'col4':[8,12,4,9]})
info3 = info.sort_values(by='col3')
print("\nSort Values:\n",info3)



print("\nDataFrame.Merge function:\n")
left=pd.DataFrame({'id': [1,2,3,4],
                    'Name': ['Sheik', 'prthzz', 'Abu', 'Vishwa'],
                    'sub': ['sub1', 'sub2', 'sub4','sub3']})

right=pd.DataFrame({
                    'id':[1,2,3,4],
                    'Name': ['Nishanth', 'Maanesh', 'Som', 'sooriya'],
                    'sub':['sub2', 'sub4', 'sub3', 'sub5']})
print(left)
print(right)
print(pd.merge(left,right,on="id"))


DataFrame.apply function:


Original DataFrame:
    S  R
0  3  9
1  3  9
2  3  9
3  3  9

Square root of DataFrame:
           S    R
0  1.732051  3.0
1  1.732051  3.0
2  1.732051  3.0
3  1.732051  3.0

Sum of each column:
 S    12
R    36
dtype: int64

Sum of each row:
 0    12
1    12
2    12
3    12
dtype: int64

Original DataFrame:
    X  Y  Z
0  2  4  6
1  1  3  5
2  5  8  7

Minimum and Maximum of each column: 

     X  Y  Z
min  1  3  5
max  5  8  7

DataFrame.Assign function:


Original DataFrame:
       Emp  ID
0   Sheik  88
1  Prthzz  70

Adding new column:
       Emp  ID  Age
0   Sheik  88   20
1  Prthzz  70   18

Adding new column:
       Emp  ID  Age     Sex
0   Sheik  88   20    Male
1  Prthzz  70   18  Female

DataFrame Sort function:

       col3      col4
3  0.288991  1.783999
2 -1.224277 -0.153198
0 -0.047223  0.018855
4 -0.260217  0.246752
1 -0.687906 -0.830533

Sort index:
        col3      col4
0 -0.047223  0.018855
1 -0.687906 -0.830533
2 -1.224277 -0.153198
3  0.

In [6]:
import pandas as pd
import numpy as hah
#Creating series from array
arr=hah.array(['p','a','n','d','a','s'])
a=pd.Series(arr)
print("Series from array:")
print(a)

Series from array:
0    p
1    a
2    n
3    d
4    a
5    s
dtype: object


In [7]:
#Series from dictionary
arr={'x':0.,'y':1.,'z':2.}
b=pd.Series(arr)
print("\n\nSeries from dictionary:\n")
print(b)



Series from dictionary:

x    0.0
y    1.0
z    2.0
dtype: float64


In [8]:
#Series using scalar
x=pd.Series(4,index=[0,1,2,3])
print("\nSeries using scalar\n")
print(x)


Series using scalar

0    4
1    4
2    4
3    4
dtype: int64


In [11]:
#Series through index
x=pd.Series([1,2,3],index=['a','b','c'])
print("\nSeries through index")
print(x)
a=pd.Series(data=[1,2,3,4])
print("\n a series:\n",a)
print("\nIndex:\n",a.index)
print("\nValues:\n",a.values)
print("\nShape:",a.shape)
print("\nDimension:",a.ndim)
print("\nSize:",a.size)


Series through index
a    1
b    2
c    3
dtype: int64

 a series:
 0    1
1    2
2    3
3    4
dtype: int64

Index:
 RangeIndex(start=0, stop=4, step=1)

Values:
 [1 2 3 4]

Shape: (4,)

Dimension: 1

Size: 4


In [15]:
import pandas as pd
d=pd.read_csv("E:/SHEIK/employees - employeess.csv")
#Get the table data
print("Get the table data:\n")
print(d)


Get the table data:

    First Name  Gender  Start Date Last Login Time  Salary  Bonus %  \
0      Douglas    Male    8/6/1993        12:42 PM   97308    6.945   
1       Thomas    Male   3/31/1996         6:53 AM   61933    4.170   
2        Maria  Female   4/23/1993        11:17 AM  130590   11.858   
3        Jerry    Male    3/4/2005         1:00 PM  138705    9.340   
4        Larry    Male   1/24/1998         4:47 PM  101004    1.389   
..         ...     ...         ...             ...     ...      ...   
995      Henry     NaN  11/23/2014         6:09 AM  132483   16.655   
996    Phillip    Male   1/31/1984         6:30 AM   42392   19.675   
997    Russell    Male   5/20/2013        12:39 PM   96914    1.421   
998      Larry    Male   4/20/2013         4:45 PM   60500   11.985   
999     Albert    Male   5/15/2012         6:24 PM  129949   10.169   

    Senior Management                  Team  
0                True             Marketing  
1                True             